name: limits

releases:
- name: os-conf
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: limits-ubuntu
  instances: 1
  networks:
  - name: default
  vm_type: default
  stemcell: default
  jobs:
  - release: os-conf
    name: limits_not_recommended
  - release: os-conf
    name: user_add
  properties:
    limits_conf: |
      small_limits  soft  nofile  1024
      small_limits  hard  nofile  4096
      big_limits  soft  nofile  16384
      big_limits  hard  nofile  16384
    users:
    - name: small_limits
      crypted_password: "$6$saltsalt$qFmFH.bQmmtXzyBY0s9v7Oicd2z4XSIecDzlB5KiA2/jctKu9YterLp8wwnSq.qc.eoxqOmSuNp2xS0ktL3nh/"
      shell: zsh # OPTIONAL: Defaults to `bash`
      sudo: false # OPTIONAL: Defaults to `true`
    - name: big_limits
      crypted_password: "$6$saltsalt$qFmFH.bQmmtXzyBY0s9v7Oicd2z4XSIecDzlB5KiA2/jctKu9YterLp8wwnSq.qc.eoxqOmSuNp2xS0ktL3nh/"

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
